# syntax=docker/dockerfile:1

FROM golang:1.26.5-bookworm

ARG AIR_VERSION=v1.67.4

RUN apt-get update \
    && apt-get install -y --no-install-recommends curl \
    && rm -rf /var/lib/apt/lists/* \
    && go install github.com/air-verse/air@${AIR_VERSION}

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 8080

CMD ["air", "-c", ".air.toml"]
