export const CATEGORY_ICON_OPTIONS = [
  { name: 'Tag', label: 'General' },
  { name: 'ShoppingCart', label: 'Súper' },
  { name: 'ShoppingBag', label: 'Compras' },
  { name: 'UtensilsCrossed', label: 'Restaurante' },
  { name: 'Utensils', label: 'Comida' },
  { name: 'Coffee', label: 'Café' },
  { name: 'Car', label: 'Auto' },
  { name: 'Fuel', label: 'Gasolina' },
  { name: 'Home', label: 'Hogar' },
  { name: 'House', label: 'Vivienda' },
  { name: 'Film', label: 'Entretenimiento' },
  { name: 'HeartPulse', label: 'Salud' },
  { name: 'Briefcase', label: 'Trabajo' },
  { name: 'Plane', label: 'Viajes' },
  { name: 'GraduationCap', label: 'Educación' },
  { name: 'Gift', label: 'Regalos' },
  { name: 'PiggyBank', label: 'Ahorro' },
  { name: 'Repeat', label: 'Suscripciones' },
  { name: 'Zap', label: 'Servicios' },
  { name: 'Wifi', label: 'Internet' },
  { name: 'Shirt', label: 'Ropa' },
  { name: 'PawPrint', label: 'Mascotas' },
  { name: 'Sparkles', label: 'Cuidado personal' },
  { name: 'Shield', label: 'Seguros' },
  { name: 'CreditCard', label: 'Deuda' },
  { name: 'Wallet', label: 'Dinero' },
  { name: 'Dumbbell', label: 'Fitness' },
  { name: 'Smartphone', label: 'Tecnología' },
  { name: 'Wrench', label: 'Mantenimiento' },
  { name: 'Baby', label: 'Hijos' },
  { name: 'TrendingUp', label: 'Inversiones' },
  { name: 'RotateCcw', label: 'Reembolsos' },
  { name: 'Award', label: 'Bonos' },
] as const

export function categoryIconLabel(name: string): string {
  return CATEGORY_ICON_OPTIONS.find((option) => option.name === name)?.label ?? name
}
